[versions]
agp = "8.7.3"
kotlin = "2.0.21"
composeBom = "2024.12.01"
hilt = "2.51.1"
ksp = "2.0.21-1.0.28"
lifecycle = "2.8.7"
navigation = "2.8.4"
coroutines = "1.8.1"
datastore = "1.1.1"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
